modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/mrmelon54/better_resource_pack_sorting/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "better_resource_pack_sorting"
version = "${version}"
displayName = "Better Resource Pack Sorting"
authors = "MrMelon54"
description = "${description}"
logoFile = "/icon.png"

[[dependencies.better_resource_pack_sorting]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_resource_pack_sorting]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "NONE"
side = "BOTH"
